FROM python:3.9

WORKDIR /backend
 
COPY web-api/requirements.txt /backend
RUN pip install -r requirements.txt

COPY web-api /backend

EXPOSE 5000
CMD ["python", "server.py"]

FROM node:lts as dependencies
WORKDIR /front-end
COPY front-end/package.json front-end/package-lock.json ./
RUN npm install --frozen-lockfile

FROM node:lts as builder
WORKDIR /front-end
COPY front-end .
COPY --from=dependencies front-end/node_modules ./node_modules
RUN npm rum build

FROM node:lts as runner
WORKDIR /front-end
ENV NODE_ENV production

COPY --from=builder /front-end/public ./public
COPY --from=builder /front-end/package.json ./package.json
COPY --from=builder /front-end/.next ./.next
COPY --from=builder /front-end/node_modules ./node_modules

EXPOSE 3000
CMD ["npm", "start"]